name: Build and Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build and Push Docker Image
      run: |
        docker build -t <your-container-registry>.azurecr.io/gofishingbotfunction:latest .
        echo ${{ secrets.AZURE_CREDENTIALS }} | docker login <your-container-registry>.azurecr.io -u <your-username> --password-stdin
        docker push <your-container-registry>.azurecr.io/gofishingbotfunction:latest

    - name: Deploy to Azure Container Instances
      uses: azure/aci-deploy@v1
      with:
        resource-group: <your-resource-group>
        dns-name-label: gofishingbot
        image: <your-container-registry>.azurecr.io/gofishingbotfunction:latest
        registry-username: <your-username>
        registry-password: ${{ secrets.AZURE_PASSWORD }}
        location: eastus
